version: '3.7'

networks:
  default:
    name: localdev
    external: true

services:
  web:
    build:
      context: ./
    container_name: rocketchilli-web
    networks:
      - default
    volumes:
      - ./web:/opt/app
    ports:
      - 80
      - 35729:35729
    environment:
      VIRTUAL_HOST: local.rocketchilli.com
